# Production environment - default production flavor
replicaCount: 3

image:
  repository: cloudwalkersinc/paved-road-service
  pullPolicy: IfNotPresent
  tag: ''  # Kargo will inject the tag

service:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP

env:
  - name: ENVIRONMENT
    value: 'production'
  - name: FLAVOR
    value: 'prod'
  - name: LOG_LEVEL
    value: 'warn'
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: db-credentials-prod
        key: url

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 60
      selectPolicy: Max

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /ready
    port: http
  initialDelaySeconds: 10
  periodSeconds: 5

ingress:
  enabled: true
  className: 'nginx'
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/rate-limit: '100'
  hosts:
    - host: paved-road.cloudwalkersinc.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: paved-road-prod-tls
      hosts:
        - paved-road.cloudwalkersinc.com
