# Dev environment - default flavor
replicaCount: 1

image:
  repository: cloudwalkersinc/paved-road-service
  pullPolicy: Always
  tag: ''  # Kargo will inject the tag

service:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP

env:
  - name: ENVIRONMENT
    value: 'dev'
  - name: FLAVOR
    value: 'dev'
  - name: LOG_LEVEL
    value: 'debug'

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /ready
    port: http
  initialDelaySeconds: 10
  periodSeconds: 5

ingress:
  enabled: true
  className: 'nginx'
  hosts:
    - host: paved-road-dev.cloudwalkersinc.com
      paths:
        - path: /
          pathType: Prefix
